import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube } from 'react-icons/ai'
import { GiSpiderWeb } from 'react-icons/gi'
import Image from 'next/image';
import nafi from '../public/nafi.png';
import { useState } from 'react';



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white dark:bg-gray-700 scroll-smooth duration-1000 snap-y snap-mandatory overflow-scroll h-screen'>
        <div className='sticky top-0 bg-gray-200 bg-opacity-50 dark:bg-gray-800 dark:bg-opacity-50 px-10 md:px-20'>
          <nav className='py-7 pb-7 flex justify-between'>
            <h1 className='text-xl uppercase font-semibold dark:text-white'>Micro Projects</h1>
            <ul className='flex items-center'>
              <li className='cursor-pointer text-2xl dark:text-white'>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} /></li>
              <li><a className='bg-gradient-to-t from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a></li>
            </ul>
          </nav>
        </div>
        <section className='h-screen px-10 md:px-20 snap-start snap-always flex flex-col justify-center'>

          <div className='flex flex-col items-center'>
            <h2 className='text-3xl font-medium py-2 text-teal-600 dark:text-teal-400'>Nafiul Haque</h2>
            <h3 className='dark:text-gray-200'>Developer and Designer</h3>
            <p className='text-gray-600 max-w-sm mx-auto dark:text-gray-400'>Freelance specialist in responsive website design, front-end development, react, tailwind CSS project etc.</p>

          </div>
          <div className='flex flex-row justify-center gap-5 text-3xl py-5 text-gray-500 dark:text-gray-300'>
            <AiFillLinkedin />
            <AiFillTwitterCircle />
            <AiFillYoutube />
          </div>
          <div className='relative bg-gradient-to-b from-teal-500 overflow-hidden rounded-full w-40 h-40 mt-5 mx-auto'>
            <Image src={nafi} layout='fill' objectFit='cover' />
          </div>
        </section>


        <section className='snap-center h-screen snap-always'>
          <div className='max-h-screen px-10 md:px-20 relative top-[100px] '>
            <h2 className='text-3xl font-bold uppercase
           text-center tracking-[14px] text-teal-500 mb-10'>Services</h2>
            <div className='grid grid-cols-2 gap-2'>
              <div className='flex flex-col items-center rounded-lg bg-gray-200 shadow-md min-h-[200px] p-4 dark:bg-gray-800'>
                <GiSpiderWeb className='text-3xl m-3 text-teal-500' />
                <h2 className='uppercase font-semibold text-2xl tracking-[2px] m-3 text-gra-900 dark:text-gray-200'>website Design</h2>
                <p className='text-gray-600 dark:text-gray-400'>Lorem ipsoum is the best layout for any bulk design</p>
              </div>
              <div className='flex flex-col items-center rounded-lg bg-gray-200 shadow-md min-h-[200px] p-4 dark:bg-gray-800'>
                <GiSpiderWeb className='text-3xl m-3 text-teal-500' />
                <h2 className='uppercase font-semibold text-2xl tracking-[2px] m-3 text-gra-900 dark:text-gray-200'>website Design</h2>
                <p className='text-gray-600 dark:text-gray-400'>Lorem ipsoum is the best layout for any bulk design</p>
              </div>
              <div className='flex flex-col items-center rounded-lg bg-gray-200 shadow-md min-h-[200px] p-4 dark:bg-gray-800'>
                <GiSpiderWeb className='text-3xl m-3 text-teal-500' />
                <h2 className='uppercase font-semibold text-2xl tracking-[2px] m-3 text-gra-900 dark:text-gray-200'>website Design</h2>
                <p className='text-gray-600 dark:text-gray-400'>Lorem ipsoum is the best layout for any bulk design</p>
              </div>
              <div className='flex flex-col items-center rounded-lg bg-gray-200 shadow-md min-h-[200px] p-4 dark:bg-gray-800'>
                <GiSpiderWeb className='text-3xl m-3 text-teal-500' />
                <h2 className='uppercase font-semibold text-2xl tracking-[2px] m-3 text-gra-900 dark:text-gray-200'>website Design</h2>
                <p className='text-gray-600 dark:text-gray-400'>Lorem ipsoum is the best layout for any bulk design</p>
              </div>
            </div>
          </div>
        </section>
      </main>

    </div>
  )
}
